---
title: "2021-11-27-Reflection-Blog-Post"
author: "Alex Prevatte"
date: "11/27/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reflection Blog Post

My thoughts on what data scientist do has not changed much since starting this course. The primary functions performed by data scientists involve data cleaning, data exploration, modeling and statistical analysis, and using this information to tell a story or to improve decision making.

I'd like to use R moving forward in my career as it is the language I am most comfortable with. However, I've had growing interest in learning Python as it is a more versatile language and seems to be used more widely in industry. I'd like to use R and Python together in the future depending on the task at hand. For much larger applications I will use Python, otherwise I plan to use R.  

Now that I've taken this course, I'd like to use parallel computing as much as I can for larger projects. This will help cut down on computation speed which is especially important when multitasking. I'd also like to incorporate RShiny into my work as well. I have never used programming to create dashboards, and I find this to be a helpful feature for explaining data science to lay audiences. 